CREATE TABLE IF NOT EXISTS sales ( 
id INT AUTO_INCREMENT PRIMARY KEY, 
product VARCHAR(50), 
category VARCHAR(50), 
amount DECIMAL(10, 2), 
sale_date DATE, 
quantity INT, 
customer_id INT, 
store_location VARCHAR(50) 
);

SELECT * FROM SALES;


SELECT 
COUNT(PRODUCT) AS TOTAL_PRODUCT,
SUM(AMOUNT) AS TOTAL_AMOUNT,
MAX(AMOUNT) AS MAX_AMT,
MIN(AMOUNT) AS MIN_AMT,
AVG(AMOUNT) AS AVG_AMT 
FROM SALES;



SELECT 'total_orders' as aggregation, count(*) AS value FROM SALES 
UNION 
SELECT 'sum_order_amount', SUM(AMOUNT) AS TOTAL_AMOUNT FROM SALES 
UNION
SELECT 'max_order_amount', MAX(AMOUNT) AS MAX_AMT FROM SALES 
UNION
SELECT 'min_order_amount', MIN(AMOUNT) AS MIN_AMT FROM SALES 
UNION
SELECT 'avg_order_amount', AVG(AMOUNT) AS AVG_AMT FROM SALES;

SELECT MAX(PRODUCT) FROM SALES;